name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview_minus: ^1.0.2
  go_router: ^13.2.1
  fl_extended:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
