name: fl_extended
description: "Some extension components and methods have been added to flutter and the routing functionality has been simplified"
version: 1.7.3
repository: https://github.com/Wayaer/fl_extended

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: FlExtendedIcons
      fonts:
        - asset: assets/FlExtendedIcons.ttf