name: fl_extended
description: "Some extension components and methods have been added to flutter and the routing functionality has been simplified"
version: 0.4.0
repository: https://github.com/Wayaer/fl_extended

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  easy_refresh: ^3.3.4
  collection: ^1.18.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: FlExtendedIcons
      fonts:
        - asset: assets/FlExtendedIcons.ttf