name: fl_extended
description: "Some extension components and methods have been added to flutter and the routing functionality has been simplified"
version: 3.0.2
repository: https://github.com/Wayaer/fl_extended

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: FlIcons
      fonts:
        - asset: assets/FlExtendedIcons.ttf